server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://thatundbuoqtrp:1c0b9d41aa6f223f45a0d8604520905b09565e0c45118efe1eea92c744e1624a@ec2-174-129-225-160.compute-1.amazonaws.com:5432/d2djqr0o9aucn6
    username: thatundbuoqtrp
    password: 1c0b9d41aa6f223f45a0d8604520905b09565e0c45118efe1eea92c744e1624a
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    genereate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
  version: 2.0
